packages:
  - "packages/*"
  - "app/*"
  - "configs/*"

catalog:
  "@pandacss/dev": ^1
  "@vitest/browser-playwright": 4.1.11
  playwright: 1.62.1
  tsdown: ^0.21.0
  vitest: 4.1.11

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
  react19:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.14
    "@types/react-dom": ^19.2.3

overrides:
  "@storybook/addon-docs>react": 18.3.1
  "@storybook/addon-docs>react-dom": 18.3.1

packageExtensions:
  lucide-react:
    peerDependencies:
      "@types/react": "*"

autoInstallPeers: false
hoist: false
publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
  workerd: true
